@startuml StreetHoop_Gameplay

class Juego
class Cancha
class Equipo

class Jugador{
- nombre
- numero
- habilidad
}

class Base{
+ pasar()
+ dirigir()
}

class Ala{
+ conducir()
+ tirar()
}

class Pivot{
+ bloquear()
+ encestar()
}

class Alero{
+ defender()
+ robar()
}

class Oponente
class JugadorOfensivo{
+ atacar()
- morir()
}

class JugadorDefensivo{
+ defender()
+ robar()
- morir()
}

class Capitán
class JugadorEstrella

class PowerUp
class AumentoVelocidad
class AumentoFuerza
class AumentoDefensa
class BalónDePoder

class Canasta
class CanastaDosPuntos
class CanastaTresPuntos
class TiroLibre

class Marcador
class Cronometro
class Faltas

class Pelota
class Accion

Base --|> Jugador
Ala --|> Jugador
Pivot --|> Jugador
Alero --|> Jugador

Oponente --|> Jugador
JugadorOfensivo --|> Oponente
JugadorDefensivo --|> Oponente
Capitán --|> Jugador
JugadorEstrella --|> Jugador

CanastaDosPuntos --|> Canasta
CanastaTresPuntos --|> Canasta
TiroLibre --|> Canasta

AumentoVelocidad --|> PowerUp
AumentoFuerza --|> PowerUp
AumentoDefensa --|> PowerUp
BalónDePoder --|> PowerUp

Juego "1" *-- "2" Equipo : administra >
Equipo "1" *-- "1..*" Jugador : contiene >

Juego "1" *-- "1" Cancha : contiene >
Cancha "1" *-- "0..*" Canasta
Cancha "1" *-- "0..*" PowerUp
Cancha "1" *-- "1" Marcador

Jugador "1" --> "0..*" PowerUp : usar
Jugador "1" --> "1" Pelota : controla

Marcador "1" o-- "0..*" CanastaDosPuntos
Marcador "1" o-- "0..*" CanastaTres
Marcador "1" o-- "0..*" TiroLibre

Accion "0..*" o-- "1" Jugador : realiza >
Accion "1" o-- "1" Pelota : utiliza >

Capitán "1" o-- "1" Bandera

@enduml